### ISSUE TITLE
Allow contributors to push branches

### ISSUE THREAD

**Issue by ejm714** [Iamshankhadeep/setup-ffmpeg#6]
I was hoping to make some edits to the README since specifying a version (e.g. `version: "4.4"`) only works if the version of the action is @1.1, not @1. However, the repo is not set up to allow contributors to push branches. If you can adjust this, I'm happy to push my fixes. If you're not open to this, here are my fixes below:

- Setup FFmpeg using inputs from github actions **(supports ffmpeg 4.1, 4.4, and 5.0 currently)** in GitHub Actions
- uses: **Iamshankhadeep/setup-ffmpeg@v1.1**
- The action uses a recent FFmpeg build provided by the following sources The action uses a recent FFmpeg build provided by the following sources **unless a version is explicitly specified**:

**Comment by Iamshankhadeep** [comment]
@ejm714 hey definately open up a PR, that will be a lot of help, thanks 🔥

**Comment by ejm714** [comment]
Hi @Iamshankhadeep, happy to open a PR but I think you need to allow this in settings. When I try to push my branch, I get this error

```
❯ git push --set-upstream origin update-readme
ERROR: Permission to Iamshankhadeep/setup-ffmpeg.git denied to ejm714.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Iamshankhadeep** [comment]
@ejm714 you need to fork this repo and push change to the fork repo and open PR. Sorry for late response, I will just update it myself. Thanks

**Comment by Iamshankhadeep** [comment]
@ejm714  https://github.com/Iamshankhadeep/setup-ffmpeg/commit/153f32ff5b742e1c96c021798003c4dfcc094705 this commit should fixe all your conserns can you have a look and let me know if it's all good or no?

**Comment by ejm714** [comment]
Looks great! Just missing a period before "The action..."
